- Editor/Interactables/InteractableFacadeEditor.cs
There was a small spelling error on the custom InteractableFacade
editor, which has now been corrected.
> fix(Interactions): fix spelling error on InteractableFacade editor - fixes #11

- Editor/Interactables/InteractableFacadeEditor.cs
- Runtime/Interactables/SharedResources/NestedPrefabs/GrabActions/Interactable.GrabAction.Follow.prefab
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableFollowAction.cs
The new Rotate Around Angular Velocity follow type allows the
interactable to follow the rotation of the interactor's angular
velocity and can be useful for interactions such as turning something
with wrist motion rather than controller positional changes.
> feat(Interactions): add rotate around angular velocity follow type

- Editor/Interactables/InteractableCreatorEditorWindow.cs
- Editor/Interactables/InteractableFacadeEditor.cs
- Runtime/Interactables/SharedResources/Scripts/Event/Proxy/InteractableFacadeEventProxyEmitter.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableControlDirectionAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableFollowAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableScaleAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableSwapAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/GrabInteractableConfigurator.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/InteractableGrabStateEmitter.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/InteractableGrabStateRegistrar.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Provider/GrabInteractableInteractorProvider.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Provider/GrabInteractableListInteractorProvider.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Provider/GrabInteractableStackInteractorProvider.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Receiver/GrabInteractableReceiver.cs
- Runtime/Interactables/SharedResources/Scripts/InteractableActionReceiverConfigurator.cs
- Runtime/Interactables/SharedResources/Scripts/InteractableActionReceiverFacade.cs
- Runtime/Interactables/SharedResources/Scripts/InteractableConfigurator.cs
- Runtime/Interactables/SharedResources/Scripts/InteractableFacade.cs
- Runtime/Interactables/SharedResources/Scripts/InteractablePropertyCache.cs
- Runtime/Interactables/SharedResources/Scripts/Operation/Extraction/InteractableConsumerContainerExtractor.cs
- Runtime/Interactables/SharedResources/Scripts/Operation/Extraction/InteractableConsumerRigidbodyExtractor.cs
- Runtime/Interactables/SharedResources/Scripts/Operation/Extraction/InteractableFacadeExtractor.cs
- Runtime/Interactables/SharedResources/Scripts/Touch/TouchInteractableConfigurator.cs
- Runtime/Interactors/SharedResources/Scripts/GrabInteractorConfigurator.cs
- Runtime/Interactors/SharedResources/Scripts/InteractorFacade.cs
Previously, the Interactables were in a namespace that was at a higher
level of the Interactors whereas Interactables should be at the same
level.
There is already an Interactables namespace used by both interactors
and interactables so the best solution is to just have a double
Interactables.Interactables namespace. Whilst this looks a bit strange
it at least buckets the code at the correct level.
> feat(Interactables): apply more specific namespace to interactables

- Documentation/API/Interactables/InteractableFacade.md
- Documentation/API/Interactables/Touch/TouchInteractableConfigurator.md
- Runtime/Interactables/SharedResources/NestedPrefabs/Interactable.TouchReceiver.prefab
- Runtime/Interactables/SharedResources/Scripts/InteractableFacade.cs
- Runtime/Interactables/SharedResources/Scripts/Touch/TouchInteractableConfigurator.cs
The InteractableFacade now has some common helper methods for
tasks like enabling/disabling the touch and grab configurations
in case of toggling the interactable behaviour.
It is also possible to get access to common sub components from
the facade such as the Rigidbody, MeshContainer, a collection
of MeshRenderers and a collection of Colliders.
The Interactable.TouchReceiver prefab has also been updated to
contain additional useful references.
> feat(Interactables): provide helper methods for common tasks

- Runtime/Interactables/SharedResources/NestedPrefabs/GrabActions/Interactable.GrabAction.Follow.prefab
The divergence states found within the divergable property
modifiers needs to be cleared when the ungrab occurs otherwise
the convergence of the source/target objects cannot occur.
> fix(interactions): clear divergence states on ungrab

- Runtime/Interactors/SharedResources/Scripts/InteractorFacade.cs
The Ungrab in the Interactor shouldn't just attempt to unregister the
consumers associated with the interactable but instead should attempt
to unregister with the interactable's consumer container as that is
the actual thing the consumers return as the registered container.
> fix(Interactions): ensure correct consumer container is unregistered

- Editor/Interactables/InteractableFacadeEditor.cs
- Runtime/Interactables/SharedResources/NestedPrefabs/GrabActions/Interactable.GrabAction.None.prefab
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableNullAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableNullAction.cs.meta
- Runtime/Interactables/SharedResources/Scripts/Grab/GrabInteractableConfigurator.cs
The secondary action can now also be set to follow, which allows the
primary action to be set to none so the primary action does nothing
whereas the secondary action will then grab the item to mimic two
hand grabbing.
The None action now has its own null action rather than just using the
base action so it can be easily identified as a nothing action.
> feat(Interactions): allow follow as standard secondary action

- Documentation/API/Interactors/InteractorFacade.md
- Documentation/API/Interactors/InteractorFacadeSettingsModifier.InteractorElement.md
- Runtime/Interactors/SharedResources/Scripts/InteractorFacade.cs
- Runtime/Interactors/SharedResources/Scripts/InteractorFacadeSettingsModifier.cs
The Interactor would require a VelocityTrackerProcessor but this
limited the usage and as it just extends the VelocityTracker then
it makes sense for the Interactor to just take a VelocityTracker
and this shouldn't break any prefab links either.
> fix(Interactions): use VelocityTracker on Interactor

- Editor/Interactables/InteractableFacadeEditor.cs
The InteractableFacadeEditor had an empty XML doc at the top of the
class which isn't needed.
> fix(Interactions): remove erroneous xml doc from editor

- Documentation/API/Interactables/Grab/Action/GrabInteractableFollowAction.md
- Documentation/API/Interactors/TouchInteractorConfigurator.md
- Runtime/Interactables/SharedResources/NestedPrefabs/GrabActions/Interactable.GrabAction.Follow.prefab
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableFollowAction.cs
- Runtime/Interactors/Prefabs/Interactions.Interactor.prefab
- Runtime/Interactors/SharedResources/Scripts/TouchInteractorConfigurator.cs
The CollisionTracker on the Interactor is now pre-warned of kinematic
state changes of any trigger collider that the Interactor is touching
and this then works inline with the new CollisionTracker changes that
allow the TriggerExit/Enter to be ignored in Unity 2019.3 and above
when kinematic changes are made to a rigidbody.
This is to ensure the changes introduced by Unity 2019.3 do not break
the events on the Interactable because now changing the kinematic
state on a Rigidbody will now cause a collsiion exit and collision
enter to occur, even though the colliding objects have not stopped
colliding. This is due to a change in the PhysX 4.11 system and Unity
did not counter this change and introduced a non-documented breaking
change.
> fix(Interactions): prepare kinematic state changes on collision tracker

- Runtime/Interactables/SharedResources/NestedPrefabs/GrabActions/Interactable.GrabAction.ControlDirection.prefab
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableControlDirectionAction.cs
The latest version of the DirectionModifier now allows for a
TargetOffset to be provided, which can be provided from any Follow
action as they also consider a TargetOffset. The first found
TargetOffset of a complimentary follow action on an interactable will
be used as the TargetOffset on the ControlDirection Directionmodifier.
> feat(prefabs): update ControlDirection to implement follow TargetOffset

- Runtime/Interactables/SharedResources/Scripts/Event/Proxy/InteractableFacadeEventProxyEmitter.cs
- Runtime/Interactors/SharedResources/Scripts/Event/Proxy/InteractorFacadeEventProxyEmitter.cs
There was an issue where an event proxy could be called but the Payload
was null causing a null exception to occur. This has now been guarded
against.
> fix(Proxy): prevent null exception in event proxies

- Runtime/Interactors/Prefabs/Interactions.Interactor.prefab
- Runtime/Interactors/SharedResources/NestedPrefabs/Interaction.Touching.prefab
- Runtime/Interactors/SharedResources/Scripts/ComponentTags/IgnoreInteractorOnColliderTag.cs
- Runtime/Interactors/SharedResources/Scripts/ComponentTags/IgnoreInteractorOnColliderTag.cs.meta
- Runtime/Interactors/SharedResources/Scripts/ComponentTags/IgnoreInteractorOnContainingTransformTag.cs
- Runtime/Interactors/SharedResources/Scripts/ComponentTags/IgnoreInteractorOnContainingTransformTag.cs.meta
A recent update to the Collision Tracker means it is now possible
to ignore specific colliders based on a rule. This is now being used
in the Interactor to ignore any collider with the
IgnoreInteractorOnColliderTag component on it. This can now be added
to any collider on an interactable to make the interactor ignore the
collider on the interactable.
This can be useful for example to ignore the blade of a sword so it
can only be grabbed by the handle.
> feat(Interactors): add ability to ignore colliders based on tag

- Runtime/Interactors/SharedResources/Scripts/Rule.meta
- Runtime/Interactors/SharedResources/Scripts/Rule/InteractorIsGrabbingRule.cs
- Runtime/Interactors/SharedResources/Scripts/Rule/InteractorIsGrabbingRule.cs.meta
- Runtime/Interactors/SharedResources/Scripts/Rule/InteractorIsTouchingRule.cs
- Runtime/Interactors/SharedResources/Scripts/Rule/InteractorIsTouchingRule.cs.meta
- Runtime/Interactors/SharedResources/Scripts/Rule/InteractorRule.cs
- Runtime/Interactors/SharedResources/Scripts/Rule/InteractorRule.cs.meta
The new rules will be able to determine if a given GameObject has
an InteractorFacade on it and if it does then whether the given
Interactor is either currently touching or grabbing something.
> feat(Rule): add rules for interactor touch and grab state

- Documentation/API/Interactables/Touch/TouchInteractableConfigurator.md
- Documentation/API/Interactors/InteractorFacade.md
- Runtime/Interactables/SharedResources/Scripts/Touch/TouchInteractableConfigurator.cs
- Runtime/Interactors/SharedResources/Scripts/GrabInteractorConfigurator.cs
- Runtime/Interactors/SharedResources/Scripts/InteractorFacade.cs
The new SimulateTouch and SimulateUntouch method on the
InteractorFacade allow for the Interactor to effectively touch an
Interactable without needing to physically collide with it in the
spatial world.
The Grab() method has also been updated so it uses this SimulateTouch
before grabbing so all of the correct events are triggered.
> feat(Interactor): add ability to simulate a touch with no collision

- Documentation/API/Interactors/GrabInteractorConfigurator.md
- Runtime/Interactors/SharedResources/Scripts/GrabInteractorConfigurator.cs
There is an issue with the newly added touch before force grab where
it may not always be desirable to have that functionality and as
the functionality has changed then it should be an option so it can
be disabled and provide the original functionality if need be.
> fix(Interactor): make touch before force grab optional

- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableControlDirectionAction.cs
The DirectionModifier now supports a PivotOffset which is now set by
the first child GameObject found within the TargetOffset GameObject.
> feat(Action): provide pivot offset from target offset first found child

- Runtime/Interactors/SharedResources/NestedPrefabs/Interaction.Touching.prefab
The Slicer component now provides a mechanism to determine if the
sliced list contents have changed so this makes it more efficient
when needing to call the interactable collision consumers.
Previously, they were being called every OnStay even if the current
touched object hadn't changed and this was very inefficeint and could
lead to a drop in framerate if touching many objects.
> fix(Touching): only call touch consumers if touch has changed - fixes #108

- Documentation/API/Interactables/Grab/GrabInteractableConfigurator.UnityEvent.md
- Documentation/API/Interactables/Grab/GrabInteractableConfigurator.UnityEvent.md.meta
- Documentation/API/Interactables/Grab/GrabInteractableConfigurator.md
- Documentation/API/Interactables/Grab/InteractableGrabStateRegistrar.RigidbodyUnityEvent.md
- Documentation/API/Interactables/Grab/InteractableGrabStateRegistrar.RigidbodyUnityEvent.md.meta
- Documentation/API/Interactables/Grab/InteractableGrabStateRegistrar.md
- Documentation/API/Interactables/Grab/README.md
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableFollowAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/GrabInteractableConfigurator.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/InteractableGrabStateRegistrar.cs
Due to the changes in PhysX, the change of a Rigidbody kinematic
state will cause the collider to call the exit, then enter events
even though the collider has not stopped intersecting.
This was fixed in the Zinnia Collision Tracker and in turn the
Interactable and Interactor connection, but anywhere else that relies
on the interactable kinematic state will not have a clear point to
know when this happens.
So a new event has been added to the GrabInteractableConfigurator
that emits the rigidbody that the kinematic state is about to change
on.
Other dependents can now listen to this event to prepare any colliding
rigidbody for the impending exit/enter.
The GrabInteractableFollowAction emits this event when it changes the
kinematic state upon grab and ungrab.
The …
> feat(Grab): emit event when kinematic state will change

- Documentation/API/Interactables/Grab/Action/GrabInteractableFollowAction.md
- Documentation/API/Interactables/Grab/Receiver/GrabInteractableReceiver.md
- Documentation/API/Interactables/InteractableActionReceiverFacade.md
- Documentation/API/Interactables/InteractableFacade.md
- Editor/Interactables/InteractableFacadeEditor.cs
- Runtime/Interactables/SharedResources/NestedPrefabs/GrabActions/Interactable.GrabAction.Follow.prefab
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableFollowAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/Receiver/GrabInteractableReceiver.cs
- Runtime/Interactables/SharedResources/Scripts/InteractableActionReceiverFacade.cs
- Runtime/Interactables/SharedResources/Scripts/InteractableFacade.cs
- Runtime/Interactors/Prefabs/Interactions.Interactor.prefab
The Interactor and Interactable now has a VelocityMultiplier on them
so the throw velocity can be multiplied on either the Interactor
or the Interactable (or both).
The Interactable Editor has also been tidied up a bit with some
horizontal lines added and a bit more indentation to make it easier
to follow the flow of data.
A number of enum properties have also had set methods added for them
as well.
> feat(Interactions): multiply velocity on interactor and interactable

- Documentation/API/Interactables/Grab/Action/GrabInteractableNullAction.md
- Runtime/Interactables/SharedResources/NestedPrefabs/GrabActions/Interactable.GrabAction.None.prefab
- Runtime/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableNullAction.cs
- Runtime/Interactables/SharedResources/Scripts/Grab/GrabInteractableConfigurator.cs
The GrabInteractableNullAction did not emit any events when the grab or
ungrab action occurred, which was technically correct because nothing
has happened, but there may be occasions where you'd want the events
to occur. This change allows the null action to be set to force the
events if required, but by default it still doesn't force the events
so no breaking changes will occur.
> feat(Action): allow null grab action to force grab/ungrab events

- Documentation/API/Interactors/GrabInteractorConfigurator.md
- Runtime/Interactors/SharedResources/Scripts/GrabInteractorConfigurator.cs
When the Interactor Force `Grab()` method was being called it would
first do a simulate touch (to ensure the events were in the right
order). Then it would do the grab, which would make the interactable
physically touch the interactor, which would call the touch logic
again, therefore breaking the untouch logic and meaning the untouched
event would not fire as it thought it was still being touched with
the second touch that had happened.
This fix resolves that by when a simulate touch occurs, the Interactor
then turns off the Interactable CollisionNotifier for a fixed update
frame so the second touch cannot occur after the simulated touch.
> fix(Interactor): prevent double touch on force grab - fixes #128

- Runtime/Interactables/SharedResources/Scripts/InteractableConfigurator.cs
When the interactable action is instantiated it was not having the position, rotation and scale reset so if the original converted object was not at the zero orientation then the action was being offset.
This fix ensures the position, rotation and scale is reset to the identity when the action is childed to the interactable.
> fix(InteractableConfigurator): reset instantiated action orientation

- Runtime/Interactables/SharedResources/Scripts/InteractableConfigurator.cs
There was an issue when instantiating a new action it was not possible to update the position, rotation or scale of any child object in the action GameObject. This has now been fixed by making the action object match the world orientation/scale of the interactable facade so when it is childed it resets to the correct zero origin.
The Instantiate method is also always called if the app is playing and not the PrefabUtility method as this is only now used at edit time in the editor.
> fix(InteractableConfigurator): set action instantiation correctly

- Editor/Interactables/InteractableFacadeEditor.cs
The icon was available in Unity 2018 but does not seem to be available in 2022 so it has been replaced with something that is similar and seems to be available in all current versions.
> fix(Editor): replace missing icon in newer unity versions

- Documentation/API/Interactables/InteractableConfigurator.md
- Documentation/API/Interactables/InteractableFacade.md
- Documentation/API/Interactables/Utility.meta
- Documentation/API/Interactables/Utility/InteractableCreator.md
- Documentation/API/Interactables/Utility/InteractableCreator.md.meta
- Documentation/API/Interactables/Utility/InteractableFactory.ActionType.md
- Documentation/API/Interactables/Utility/InteractableFactory.ActionType.md.meta
- Documentation/API/Interactables/Utility/InteractableFactory.md
- Documentation/API/Interactables/Utility/InteractableFactory.md.meta
- Documentation/API/Interactables/Utility/README.md
- Documentation/API/Interactables/Utility/README.md.meta
- Runtime/Interactables/SharedResources/Scripts/InteractableConfigurator.cs
- Runtime/Interactables/SharedResources/Scripts/InteractableFacade.cs
The IsVisible property on the getter will return whether the interactable object is in its `visible` state which is the renderers are active and the colliders working.
When the IsVisible property is set to `false` then all of the renderers are disabled and all of the colliders are set to trigger colliders to mimmic the GameObject becoming invisible but still active within the scene.
> feat(Interactions): add IsVisible property to interactable

- Runtime/Interactables/Prefabs/Interactions.Interactable.prefab
The collider scale on the interactable default mesh was set to 2,2,2 which meant the collider was twice as big as the mesh.
This has now been fixed.
> fix(Prefabs): reset default mesh collider scale to 1,1,1

- Runtime/Interactables/SharedResources/Scripts/InteractableConfigurator.cs
Older versions of Unity cannot destroy a nested prefab, so as the Controllables for example nest the Interactable prefab, if the Interactable prefab is attempted to change the grab action then this tries to delete the nested grab action but will raise an InvalidOperationException because this nested prefab cannot be deleted.
The fix for this is to just disable the hard wired prefab and then create a new temporary prefab that can be continually updated.
> fix(Configurator): catch error on destroy nested prefabs

- Editor/Interactables/InteractableCreatorEditorWindow.cs
- Runtime/Interactables/Prefabs/Interactions.Interactable.prefab
- Runtime/Interactables/SharedResources/NestedPrefabs/Interactable.GrabEvent.Set.prefab
- Runtime/Interactables/SharedResources/NestedPrefabs/Interactable.GrabEvent.Stack.prefab
- Runtime/Interactables/SharedResources/NestedPrefabs/Interactable.GrabReceiver.prefab
- Runtime/Interactables/SharedResources/Scripts/InteractableConfigurator.cs
- Runtime/Interactables/SharedResources/Scripts/InteractableFacade.cs
- Runtime/Interactables/SharedResources/Scripts/Utility/InteractableCreator.cs
- Runtime/Interactables/SharedResources/Scripts/Utility/InteractableFactory.cs
The InteractableCreatorEditorWindow now has an extra button that instead of nesting the selected GameObject inside an interactable prefab it will instead embed the newly created interactable prefab as a child of the selected GameObject.
> feat(Editor): add embed interactable into gameobject option

- Documentation/API/Interactables/Grab/Action/GrabInteractableFollowAction.md
- Documentation/API/Interactables/InteractableConfigurator.md
- Documentation/API/Interactables/InteractableFacade.md
- Documentation/API/Interactables/Utility/InteractableCreator.md
- Documentation/API/Interactables/Utility/InteractableFactory.md
- Runtime/Interactables/Prefabs/Interactions.Interactable.prefab
A new path has been added that when an interactable is grabbed, the specific collider on the interactable is emitted to a Rules Matcher so custom logic can be applied before the grab mechanics execute.
> feat(Prefabs): match rules to the grabbed interactable collider

- Runtime/Interactables/Prefabs/Interactions.Interactable.prefab
- Runtime/Interactables/SharedResources/NestedPrefabs/Interactable.GrabReceiver.prefab
- Runtime/Interactables/SharedResources/NestedPrefabs/Interactable.TouchReceiver.prefab
A new Rules Matcher has been added that can be used to process the touched collider of the interactable in a similar way to how the grabbed collider matcher works. This makes it possible to know which collider has been touched on the interactable and do something with this information before the rest of the touch logic is run.
The touch (and now the grab) collider logic only runs if the interactor is not in the disallowed interactors list for the interaction type.
> feat(prefabs): add rules matcher for touched colliders

- Runtime/Interactors/SharedResources/Scripts/GrabInteractorConfigurator.cs
The Grab method on the GrabInteractorConfigurator was able to be run even when the GameObject was disabled, which is not in keeping with Zinnia patterns. This has now been fixed.
> fix(Interactors): prevent grab on disabled game object

- Runtime/Interactables/SharedResources/Scripts/Grab/InteractableGrabDropRestrictor.cs
When calling `DoEnableDrop` it would go into an infinite loop as the main method was being called rather than the sub method.
> fix(Grab): prevent infinite loop in grab drop restrictor

- Runtime/Interactables/SharedResources/NestedPrefabs/Interactable.GrabReceiver.prefab
The DisallowedGrabInteractors rule was causing an issue when using precision grab due to the collision consumer still being published for an invalid interactor which was causing the precision point container to be created for an invalid interactor. This meant that any other valid interactor was not becoming a precision point grab as the detached precision point for the invalid interactor still existed.
The solution is to modify the GrabReceiver prefab so it turns off the OutputActiveCollisionConsumer logic if the interactor is disallowed and then the precision point cannot be created prior to a grab event.
> fix(Prefabs): disallow collision consumers for invalid interactor

- Editor/Interactables/InteractableFacadeEditor.cs
- Runtime/Interactables/Prefabs/Interactions.Interactable.prefab
- Runtime/Interactables/SharedResources/NestedPrefabs/Interactable.Common.prefab
The disallowed touch and grab interactors used to only work on a ListContainsRule and this was hard coded into the facade editor. This meant that no other rule could be replaced as it would throw an error due to the custom editor.
This feature introduces a new AnyRule at the heart of both the touch/grab disallowed logic with the first rule being the existing ListContainsRule, so all of the existing logic still works and that ListContainsRule must be at the zero index of the AnyRule list.
But now the AnyRule can also contain any other rule that is required to disallow touch or grab interactors.
> feat(Facade): allow multiple rules for disallowed touch/grab types
